name:                haskell-json-patch
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- text
- containers
- deepseq

library:
  source-dirs: src

executables:
  haskell-json-patch-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-json-patch
    - strings

tests:
  haskell-json-patch-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-json-patch
    - tasty
    - tasty-hunit
